### ISSUE TITLE
How long are images cached for?

### ISSUE THREAD

**Issue by robb-j** [11ty/api-indieweb-avatar#14]
Since deploying my tweetback, I've updated the favicon on my personal site and I figured the indie avatar would eventually update, but it doesn't seem to have?

If I take the trailing slash (%2f) off it gets the updated icon

* My tweetback — https://tweets.r0b.io/
* The icon URL it uses — https://v1.indieweb-avatar.11ty.dev/https%3A%2F%2Fwww.r0b.io%2F/
* Slightly different variant — https://v1.indieweb-avatar.11ty.dev/https%3A%2F%2Fwww.r0b.io/

Thanks,
Rob

**Comment by zachleat** [comment]
The cache is invalidated with a build but builds do not happen often! I think I should probably at least add a weekly `ttl`.

You could PR it if you like!

https://github.com/11ty/api-indieweb-avatar/blob/v1/functions/avatar/index.js#L27

https://docs.netlify.com/configure-builds/on-demand-builders/#time-to-live-ttl

**Comment by robb-j** [comment]
Ok I'll give it a bash

**Comment by zachleat** [comment]
It’s live!

**Comment by zachleat** [comment]
Closed by #15
