### ISSUE TITLE
Add BIMI Support

### ISSUE THREAD

**Issue by kingkool68** [11ty/api-indieweb-avatar#3]
The BIMI standard is specifically designed for this use case. It's a DNS text record pointing to an SVG avatar. I thought this was a really neat idea and went and added support for it. Later I realized big global corporate email clients will only show BIMI avatars that are verified with a VMC that you have to pay a yearly fee to DigiCert or Entrust for AND you need to have a registered service mark. This effectively limits the technology to big global corporations. 

I would love to see this implemented in more indie applications.

See https://www.litmus.com/blog/what-is-bimi-and-why-should-email-marketers-care/

**Comment by inetbiz** [comment]
@zachleat & @kingkool68 Read gitlab issue [.well-known idea](https://git.linux-kernel.at/oliver/ivatar/-/issues/12 ). I propose  **[OFC](https://github.com/dstl/Open-Federated-Search "Open Federated Search")**Open Federated Search to populate a return and possibly a SRV record? Quick solution not involving DNS is add this: to public sources in the header: https://gist.github.com/inetbiz/394b6181a84eb365f2957acb1ebf4c0d Just add one more for chosen Avatar. Could discuss rel=me searching for a person schema. Just saw that those 'xmlns' were removed. So, an alternative? Open Graph.? The xmlns would need custom attributes to populate more data? https://github.com/niallkennedy/open-graph-protocol-examples/blob/master/profile.html

**Comment by inetbiz** [comment]
I also found this from Mozilla: https://developer.mozilla.org/en-US/docs/Web/OpenSearch

**Comment by zachleat** [comment]
Some notes on BIMI here, I don’t think this will happen https://shkspr.mobi/blog/2022/08/dns-esoterica-bimi-svg-in-dns-txt-wtf/
