### ISSUE TITLE
Additional support for Apple’s `precomposed` icon options

### ISSUE THREAD

**Issue by zachleat** [11ty/api-indieweb-avatar#5]
via https://mathiasbynens.be/notes/touch-icons and @nhoizey

also optionally support root directory lookups for:

```

    apple-touch-icon-57x57-precomposed.png
    apple-touch-icon-57x57.png
    apple-touch-icon-precomposed.png
    apple-touch-icon.png

```

though that seems unlikely as additional HTTP requests here are not ideal

**Comment by nhoizey** [comment]
I think `apple-touch-icon.png` is enough here, but maybe some deep dive into [httparchive](https://httparchive.org/) data can help see which are used the most.
